### ISSUE TITLE
Unable to leverage parallelism from spark to Orientdb

### ISSUE THREAD

**Issue by hilesha** [orientechnologies/spark-orientdb#13]
Hi,

i was loading csv data (600 MB) into orientdb(2 node distributed cluster) into a class using following command

df.write.format("org.apache.spark.orientdb.documents").option("dburl","remote:localhost:2424/mydb").option("class", "sales").option("user","admin").option("password","admin").save()

df is loaded with a csv having following schema using this command
val df = sqlContext.read.option("header","TRUE").schema(customSchema).csv("path of csv file")

val customSchema = StructType(Array(
StructField("key", LongType, true),
StructField("date", DateType, true),
StructField("code", IntegerType, true),
StructField("quantity", IntegerType, true),
StructField("revenue", DoubleType, true),
StructField("count_flag", StringType, true),
StructField("updated_on", DateType, true)))

when i look into the cluster list which are created inside of the class "sales", it creates 8 clusters but unfortunately it is trying to write into a single default cluster(sales)  instead of all cluster(sales_1 to sales_7) which is becoming a bottleneck.

i tried to modify my save command by adding cluster option, still the api gives me single cluster specification and not a way to add data on all cluster.

df.write.format("org.apache.spark.orientdb.documents").option("dburl","remote:localhost:2424/mydb").option("class", "sales").option("user","admin").option("password","admin").option("cluster","sales_1").save()

is this a limitation of spark connector? i would appreciate the inputs from committers .

**Comment by sbcd90** [comment]
Hello @hilesha ,

Thanks for raising this issue.
Yes, this is a limitation for the current spark connector.

I would say, enhancing the api to just support multiple clusters is not sufficient.
May be support for a generic partitioner interface is required, where users supply in which cluster a particular record belonging to a class should be saved.

**Comment by sbcd90** [comment]
Hello @hilesha ,
I provided a PR to fix this issue.
Here is a testcase that should solve your issue: https://github.com/orientechnologies/spark-orientdb/blob/master/src/it/scala/org/apache/spark/orientdb/documents/OrientDBIntegrationSuite.scala#L635-#L674

Please let me know if you have further issues related to your usecase.

**Comment by sbcd90** [comment]
There are no updates for this issue. Hence closing this issue.
