### ISSUE TITLE
Any plan to support EMBEDDEDSET, EMBEDDEDLIST, EMBEDDEDMAP and LINKEDLIST, LINKEDSET, LINKEDMAP data type?

### ISSUE THREAD

**Issue by ChenShuai1981** [orientechnologies/spark-orientdb#3]
Any plan to support EMBEDDEDSET, EMBEDDEDLIST, EMBEDDEDMAP and LINKEDLIST, LINKEDSET, LINKEDMAP data type?

**Comment by sbcd90** [comment]
Hi @ChenShuai1981 , I hope this resolves your issue..Plz let me know
