### ISSUE TITLE
Empty result set

### ISSUE THREAD

**Issue by krunarsson** [orientechnologies/spark-orientdb#7]
When I query my orient graph I always get an empty result set, but count returns correct number of records. Is this an issue or am I doing something wrong. 

To recreate this issue:
Simple create class and insert statements to create the test data. 

> CREATE CLASS Demo EXTENDS V
> INSERT INTO Demo(first_name, last_name, address, amount) VALUES ("Bill", "Tom", "Street 45", 4554)
>  INSERT INTO Demo(first_name, last_name, address, amount) VALUES ("John", "Karl", "Road 3", 4544)
>  INSERT INTO Demo(first_name, last_name, address, amount) VALUES ("Paul", "Smith", "Street 22", 1122)`

Scala code to query the graph

```
import org.apache.spark.sql.SparkSession

object SparkOrientDemo
{
  def main(args: Array[String]): Unit =
  {
    val spark = SparkSession.builder().master("local").appName("Spark Orient Demo").getOrCreate()

    val data = spark.read.format("org.apache.spark.orientdb.graphs")
      .option("dburl", "remote:192.168.1.200/testing")
      .option("user", "admin")
      .option("password", "admin")
      .option("vertextype", "Demo")
      .option("query", "select * from Demo")
      .load()

    data.show()

    val count = data.count()
    println("Dataset size: " + count);

    spark.close()
  }
}
```

Results:

```
++
||
++
||
||
||
++
```

`Dataset size: 3`

**Comment by sbcd90** [comment]
Hello @krunarsson,

The latest master branch contains a minor fix for this issue. However, the schema still needs to be specified in your code snippet like shown below.

```scala
object TestOrientDBDataSource extends App {

  val spark = SparkSession.builder().master("local").appName("Spark Orient Demo").getOrCreate()

  val data = spark.read.format("org.apache.spark.orientdb.graphs")
                .option("dburl", "remote:127.0.0.1:2424/GratefulDeadConcerts")
                .option("user", "root")
                .option("password", "root")
                .option("vertextype", "Demo")
                .option("query", "select * from Demo")
                .schema(StructType(Seq(StructField("first_name", StringType),
                  StructField("last_name", StringType),
                  StructField("address", StringType),
                  StructField("amount", IntegerType))))
                .load()

  data.show()

  val count = data.count()
  println(count)

  spark.close()
}
```
This fix will be part of next release.

**Comment by krunarsson** [comment]
Hi, 
Thank you for reacting so quickly on this issue. I can now see the result set, but I think there are still some issues. I am going to post it here in the comment, but please let me know if you think this should be a new issue. 

I am getting exceptions (see below) if I remove the data.show() from the example. I am not able to do only count how many rows are in data, but if I do data.show() before everything is working fine. 

> 17/09/19 10:17:55 INFO OrientDBVertexRelation: count query
> Exception in thread "main" java.lang.NullPointerException
> 	at org.apache.spark.orientdb.graphs.OrientDBGraphVertexWrapper.genericQuery(OrientDBGraphWrapper.scala:250)
> 	at org.apache.spark.orientdb.graphs.OrientDBVertexRelation.buildScan(OrientDBRelation.scala:67)
> 	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$8.apply(DataSourceStrategy.scala:260)
> 	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$8.apply(DataSourceStrategy.scala:260)
> 	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:303)
> 	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:302)
> 	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:376)
> 	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:298)
> 	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:256)
> 	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:60)
> 	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:60)
> 	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
> 	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
> 	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:61)
> 	at org.apache.spark.sql.execution.SparkPlanner.plan(SparkPlanner.scala:47)
> 	at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1$$anonfun$apply$1.applyOrElse(SparkPlanner.scala:51)
> 	at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1$$anonfun$apply$1.applyOrElse(SparkPlanner.scala:48)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)
> 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:300)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:298)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:298)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:321)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:179)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:319)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:298)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:298)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:298)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:321)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:179)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:319)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:298)
> 	at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1.apply(SparkPlanner.scala:48)
> 	at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1.apply(SparkPlanner.scala:48)
> 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
> 	at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1$$anonfun$apply$1.applyOrElse(SparkPlanner.scala:51)
> 	at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1$$anonfun$apply$1.applyOrElse(SparkPlanner.scala:48)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)
> 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:300)
> 	at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1.apply(SparkPlanner.scala:48)
> 	at org.apache.spark.sql.execution.SparkPlanner$$anonfun$plan$1.apply(SparkPlanner.scala:48)
> 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
> 	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:78)
> 	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:76)
> 	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:83)
> 	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:83)
> 	at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2541)
> 	at org.apache.spark.sql.Dataset.count(Dataset.scala:2216)
> 	at com.activitystream.demos.SparkOrientDemo$.main(SparkOrientDemo.scala:163)
> 	at com.activitystream.demos.SparkOrientDemo.main(SparkOrientDemo.scala)

**Comment by sbcd90** [comment]
Hi @krunarsson , 
Can you please have a look if this issue is fixed now? Please consider the latest master branch for the fix.

**Comment by krunarsson** [comment]
Hi @sbcd90,

Sorry for late answer, I am not able to reproduce this any more, so it seems to be resolved. Thanks for the fix.
